services:
  centralizedtransmissionandremoteloading:
    image: leraptor65/centralizedtransmissionandremoteloading:latest
    container_name: centralizedtransmissionandremoteloading
    ports:
      - "${PORT:-1337}:1337"
    volumes:
      - ./data:/usr/src/app/data
    environment:
      - PORT=1337
      - TARGET_URL=${TARGET_URL:-https://www.google.com/}
    restart: always
