services:
  centralizedtransmissionandremoteloading:
    image: leraptor65/centralizedtransmissionandremoteloading:latest
    container_name: centralizedtransmissionandremoteloading
    ports:
      - "1337:1337" # Host:Container
    volumes:
      - .:/usr/src/app/config_mount
      # environment:
      # - PORT=1337 # Internal app port (defaults to 1337)
    restart: always
