services:
  ctrl:
    image: leraptor65/centralizedtransmissionandremoteloading:latest
    container_name: ctrl_app
    ports:
      - "${CTRL_PORT}:1337"
    env_file:
      - .env
    environment:
      - SCRIPT_DIR=/host
      - DATA_DIR=/app/data
    volumes:
      - ./data:/app/data
      - ./:/host
    security_opt:
      - seccomp=unconfined
    restart: unless-stopped
