services:
  ctrl:
    image: leraptor65/centralizedtransmissionandremoteloading:latest
    container_name: ctrl
    ports:
      - "1337:1337" # Host:Container
    env_file:
      - .env
    volumes:
      - ./data:/root/data
    restart: always
