services:
  app:
    build: .
    image: centralizedtransmissionandremoteloading:dev
    container_name: centralizedtransmissionandremoteloading
    ports:
      - "1337:1337"
    volumes:
      - .:/usr/src/app/config_mount
      # environment:
      # - PORT=1337
    restart: unless-stopped
